[build]
publish = "out"
command = "pnpm build"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

[[redirects]]
  from = "http://willowy-jalebi-d3e8a9.netlify.app/*"
  to = "http://www.isabellmartins.de/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://willowy-jalebi-d3e8a9.netlify.app/*"
  to = "https://www.isabellmartins.de/:splat"
  force = true
  status = 301